### ISSUE TITLE
Using “Search Beer” Box to search for beers

### ISSUE THREAD

**Issue by khan-mo** [khan-mo/BeerCo#1]
**Test-Case 1, User-Case 1**
**Issue 1**: Using “Search Beer” Box to search for beers
**Description:** When a user enters a name of a beer in the search box, no results appear on the screen, besides the name of the beer itself, which is not a clickable link to the beer and or it’s information, it only shows the text itself. User should be able to click on the results to access the beer and/or it’s details/information.

**Comment by Sham1242** [comment]
Search box wasn't necessary so it was removed
