### ISSUE TITLE
Sorting by Brewer not working as it should

### ISSUE THREAD

**Issue by khan-mo** [khan-mo/BeerCo#2]
**Test-Case 2**

**Test case based on Use-Case 1**

**Issue #1**: Sorting by Brewer not working as it should

**Description**: Sorting of the beers is done; however, it is unclear as to what exactly is getting sorted when a user selects the “Brewer” option in the sorting drop down menu. Is the list getting sorted by “Beer name”? Was the goal to sort them alphabetically by First or last name of the beer/brand/business name?

**Expected result:** Sorting by brewer function should be functional and clear to the understanding of a user

**Comment by Sham1242** [comment]
Fixed; sql pull request was not requesting ints but chars
