### ISSUE TITLE
Sorting by ABV, IBU, SRM not working as it should

### ISSUE THREAD

**Issue by khan-mo** [khan-mo/BeerCo#3]
**Test-Case 2**

**Test case based on Use-Case 1**

**Issue 2:** Sorting by ABV, IBU, SRM not working as it should

**Description**: Sorting of the beers by ABV is done; however, it is unclear as to how exactly it is getting sorted. When a user clicks “ABV” in the sorting drop down menu, the beers list shown sorted by abv goes from "Heady Topper, 8 abv" on the top of the list, while “Hunahpus Imperial stout, 11 abv” shows all the way at the bottom of the sorted list. Was the goal to sort the beers from lowest abv to highest abv? In the sorted list, beers with ABV of 15, 13.3 and 12 are showed in the middle of the list.

**Expected result:** Sorting of the beers list should be done correctly, either from lowest to highest abv or from highest to lowest abv.

**Comment by Sham1242** [comment]
Fixed; sql pull request was not requesting ints but chars
