### ISSUE TITLE
Sorting by IBU & SRM not working as it should

### ISSUE THREAD

**Issue by khan-mo** [khan-mo/BeerCo#4]
**Test-Case 2**

**Test case based on Use-Case 1**

**Issue #3:** Sorting by IBU & sorting by SRM functions are not working properly

**Description**: The sorting by IBU is unclear; when a user clicks sort by IBU, it does not provide the user with a list that is sorted. Also Is sorting by IBU and SRM done so that it sorts the list of beers with highest IBU & SRM on top and beers with lowest IBU and SRM on the bottom? If yes, can we implement the same method of sorting to when a user sorts the beers by ABV.

**Expected result:** Sorting should be done in either ascending order or descending order. All of the sorting options should give similar results. Ex: If sorting by ABV is done in ascending order, then sorting by IBU & sorting by SRM should also be done in ascending order.

**Comment by Sham1242** [comment]
Fixed; sql pull request was not requesting ints but chars
