### ISSUE TITLE
Unable to scroll page up/down while adding a new beer/it’s information

### ISSUE THREAD

**Issue by khan-mo** [khan-mo/BeerCo#7]
**Test-Case 5**

**Test case based on Use case 3**

**Issue #1:** Admin is unable to scroll page up/down while adding a new beer/it’s information

**Description:** Admin is unable to scroll page down when adding in information of a new beer. The tab button on keyboard is the only way to scroll down the table/page to enter the new beer information.

**Expected result:** Admin should be able to scroll a page up and/or down when needed in order to have smooth access and experience with the website while entering in new beer information.

**Comment by Sham1242** [comment]
Fixed; rows were not correctly ordered
