### ISSUE TITLE
 Search Count is not updating on analytics page

### ISSUE THREAD

**Issue by khan-mo** [khan-mo/BeerCo#8]
**Test-Case 8**

**Test Case based on Use case 4**

**Issue #1:** Search Count not updating on analytics page

**Issue Description**: The "analytics page" or “beer data” page accessible to admin does not update the count of the searches for a particular beer even when the beer is searched for on the website by a user

**Expected result:** Search count of a beer should be updated after a user enters the website and searches for that particular beer.

**Comment by Sham1242** [comment]
Fixed; search count variable was misspelled
